version: "3"

services:
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - /home/jaisonpr/workspace/jimu/database/mongodb/data:/data/db

  backend-api:
    container_name: backend-api
    build: ./backend
    command: "node server.js"
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"

  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   ports:
  #     - 4200:80
  #   links:
  #     - backend-api
